# Generated by Django 4.1.2 on 2022-11-15 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_usartuser_description_alter_usartuser_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usartuser",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
