# Generated by Django 4.1.2 on 2022-11-17 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_remove_usartuser_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usartuser",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
