# Generated by Django 4.1.2 on 2022-11-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_usartuser_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usartuser",
            name="photo",
            field=models.ImageField(default="default.jpg", upload_to="images/"),
        ),
    ]
