# Generated by Django 4.1.2 on 2022-11-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_usartuser_photo"),
        ("authentication", "0007_idchats"),
    ]

    operations = []
