# Generated by Django 4.1.2 on 2022-12-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_idchats_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="idchats",
            name="id_1_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="idchats",
            name="id_2_active",
            field=models.BooleanField(default=True),
        ),
    ]
