# Generated by Django 4.1.2 on 2022-12-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_idchats_id_1_active_idchats_id_2_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usartuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
