# Generated by Django 4.1.2 on 2022-11-17 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_auction_alter_publication_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="purchasehistory", options={},),
        migrations.RemoveField(model_name="purchasehistory", name="author",),
        migrations.RemoveField(model_name="purchasehistory", name="publication_title",),
        migrations.RemoveField(model_name="purchasehistory", name="user",),
        migrations.AddField(
            model_name="purchasehistory",
            name="pub_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase",
                to="catalog.publication",
            ),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("PR", "Processing"),
                    ("IT", "In Transit"),
                    ("DL", "Delivered"),
                    ("RE", "Returned"),
                ],
                default="PR",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stars", models.FloatField()),
                ("review", models.TextField()),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("last_updated", models.DateField(auto_now=True)),
                (
                    "reviewed_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pub_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Fav",
                        to="catalog.publication",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Faver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blocked_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("reviewer_id", "reviewed_id"),
                name="unique_reviewer_reviewed_combination",
            ),
        ),
        migrations.AddConstraint(
            model_name="fav",
            constraint=models.UniqueConstraint(
                fields=("pub_id", "user_id"),
                name="unique_publication_user_fav_combination",
            ),
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.UniqueConstraint(
                fields=("blocked_id", "blocker_id"),
                name="unique_blocked_blocker_combination",
            ),
        ),
    ]
