# Generated by Django 4.1.2 on 2022-11-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='user',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
