# Generated by Django 4.1.2 on 2022-12-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_alter_purchasehistory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasehistory",
            name="address",
            field=models.CharField(
                default="Gran Via Corts Catalanes, 585", max_length=1000
            ),
            preserve_default=False,
        ),
    ]
