# Generated by Django 4.1.2 on 2022-10-30 21:01

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('review', models.FloatField()),
            ],
            options={
                'ordering': ['title', 'description', 'author', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='publications/default.jpg', upload_to=catalog.models.user_directory_path)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='catalog.publication')),
            ],
        ),
    ]
