# Generated by Django 4.0.2 on 2022-11-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('tag', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['title', 'description', 'author', 'tag'],
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
