# Generated by Django 4.1.2 on 2022-10-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationimage',
            name='test',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
