# Generated by Django 4.1.2 on 2022-10-30 22:34

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_publicationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='publications/default.jpg', upload_to=catalog.models.user_directory_path)),
                ('test', models.CharField(default='test', max_length=10)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='catalog.publication')),
            ],
        ),
    ]
