# Generated by Django 4.1.2 on 2022-10-31 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_publicationimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationimage',
            name='test',
        ),
    ]
