# Generated by Django 4.1.2 on 2022-11-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_auction_alter_publication_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationimage",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to=""),
        ),
    ]
