# Generated by Django 4.1.2 on 2022-11-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_publicationimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationimage",
            name="image",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
    ]
