# Generated by Django 4.1.2 on 2022-11-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_commission_pub_id_alter_commission_user_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="commission",
            name="unique_publication_user_commission_combination",
        ),
    ]
