# Generated by Django 4.1.2 on 2022-11-30 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "catalog",
            "0008_remove_commission_unique_publication_user_commission_combination",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="commission",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="pub_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publication",
                to="catalog.publication",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commission",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
