# Generated by Django 4.1.2 on 2022-12-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_complaint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="description",
            field=models.CharField(max_length=770),
        ),
    ]
