name: Python + Selenium CI 

env:
  ENV: "TEST"

on:
  push:
    branches:
      - development

  pull_request:
    branches:
      - development

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.0
      - name: Environment Test
        env: 
          THISVAR: imhereuwu
        run: |
          python ${GITHUB_WORKSPACE}/usArt_backend/environmenttest.py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${GITHUB_WORKSPACE}/usArt_backend/requirements.txt
      - name: Coverage report
        run: |
          cd ./usArt_backend/
          coverage run manage.py test
          coverage report --fail-under=85
